import XCTest
@testable import CodexConfigCore

private actor ScriptedTransport: DetectionTransport {
    enum Reply { case json(Int, String); case timeout }
    private let handler: @Sendable (URLRequest, Int) -> Reply
    private(set) var requests: [URLRequest] = []
    /// `handler` receives how many times this exact body was already sent (0 = first try).
    init(_ handler: @escaping @Sendable (URLRequest, Int) -> Reply) { self.handler = handler }
    func send(_ request: URLRequest) async throws -> (Data, HTTPURLResponse) {
        let repeats = requests.filter { $0.httpBody == request.httpBody }.count
        requests.append(request)
        switch handler(request, repeats) {
        case .timeout: throw URLError(.timedOut)
        case .json(let status, let body):
            return (Data(body.utf8), HTTPURLResponse(url: request.url!, statusCode: status, httpVersion: nil, headerFields: nil)!)
        }
    }
}

private struct SplitMix64: RandomNumberGenerator {
    var state: UInt64
    mutating func next() -> UInt64 {
        state &+= 0x9E3779B97F4A7C15
        var z = state
        z = (z ^ (z >> 30)) &* 0xBF58476D1CE4E5B9
        z = (z ^ (z >> 27)) &* 0x94D049BB133111EB
        return z ^ (z >> 31)
    }
}

private func json(_ object: Any) -> String {
    String(data: try! JSONSerialization.data(withJSONObject: object), encoding: .utf8)!
}

final class ModelTraceTests: XCTestCase {
    struct Expected {
        let prediction: String
        let used: Int
        let beta: Double
        let results: [(String, Double, Double, Double, Double)]
        let families: [(String, Double)]
        let diagnostics: [(Int, Int, Bool)]
    }
    // Generated by running upstream ModelTrace static/fingerprint-core.js (commit d4131b3) under node.
    static let jsReference: [String: Expected] = [
        "claude": Expected(prediction: "claude-opus-4-7", used: 3, beta: 11.99999999999999,
          results: [
            ("claude-opus-4-7", 0.9999900807019094, 0.7223086506889571, 2.4082934688051725, 0.9999900807020576),
            ("claude-opus-4-8", 9.901253081875371e-06, 0.659784730315508, 1.448056859175218, 9.901253081876838e-06),
            ("claude-opus-5", 1.3642697271192968e-08, 0.6308107902863906, 0.8991225073403136, 1.364269727119499e-08),
            ("claude-sonnet-5", 3.852696999071538e-09, 0.6284241334168341, 0.7937532608627421, 3.8526969990721085e-09),
            ("claude-sonnet-4-6", 3.950964892402895e-10, 0.6122422344789455, 0.6039700367257453, 3.950964892403481e-10),
            ("claude-haiku-4-5-20251001", 1.5436946579235486e-10, 0.6079283380176465, 0.5256549405585071, 1.5436946579237774e-10),
            ("gpt-5.6-terra", 1.2814913717986075e-13, 0.6067483491469692, -0.06550417750051432, 0.8635950725712984),
            ("gpt-6-astra", 1.855981236191053e-14, 0.6088701744917095, -0.22652051936710524, 0.125074291222873),
            ("gpt-5.6-sol", 7.261128936260376e-16, 0.6019685737529711, -0.4966078854404496, 0.004893263668141809),
            ("gpt-5.4", 5.59114344875588e-16, 0.5997333400224627, -0.5183871770080143, 0.003767863006059859),
            ("gpt-6-sol", 3.081578699024216e-16, 0.6026789610748899, -0.5680323260506702, 0.0020766711651619384),
            ("claude-sonnet-5-5", 6.894175258017658e-17, 0.5900697478739803, -0.6928115121916062, 6.89417525801868e-17),
            ("gpt-6-luna", 4.318437074382298e-17, 0.5905730382940959, -0.7317934572860046, 0.0002910188129797144),
            ("gpt-5.6-luna", 4.032069952889071e-17, 0.5907807691829672, -0.737511262987003, 0.0002717205765256618),
            ("claude-opus-4-6", 1.7173451402296388e-17, 0.5937325151829433, -0.8086362883871191, 1.7173451402298933e-17),
            ("claude-opus-5-5", 4.957297536278218e-18, 0.5904150999918119, -0.9121782823490854, 4.957297536278953e-18),
            ("gpt-5.5", 4.466396404853002e-18, 0.593023379174497, -0.9208681849001269, 3.0098976959693376e-05)
          ],
          families: [("gpt", 1.483903061168529e-13), ("claude", 0.9999999999998518)],
          diagnostics: [(300, 165, true), (310, 171, true), (320, 176, true)]),
        "gptOne": Expected(prediction: "gpt-6-luna", used: 1, beta: 7.227892857612239,
          results: [
            ("gpt-6-luna", 0.9916007967686411, 0.4647804650117794, 1.9811480714742566, 0.9916036144251892),
            ("gpt-6-sol", 0.006584874774223176, 0.4606075244327019, 1.2873711458511976, 0.006584893485296812),
            ("gpt-5.4", 0.0014879906887618147, 0.4591068280473719, 1.0815921354738365, 0.0014879949169216964),
            ("gpt-5.6-sol", 0.00019763218168490773, 0.4566472029480758, 0.8022888360531966, 0.00019763274326131292),
            ("gpt-5.5", 0.00010481079422053767, 0.4577405397237063, 0.7145383834033063, 0.00010481109204282826),
            ("gpt-5.6-terra", 1.6884870930404197e-05, 0.45545162733565636, 0.46194211626602333, 1.6884918909154612e-05),
            ("gpt-5.6-luna", 3.193590489908496e-06, 0.45055374149261895, 0.23154686646034978, 3.1935995645695745e-06),
            ("claude-opus-5-5", 1.5867498552787e-06, 0.4516042116133535, 0.13477481476394385, 0.5584168491077387),
            ("claude-opus-4-6", 1.104249116187749e-06, 0.4503803880047972, 0.08461880885474188, 0.3886128049989717),
            ("gpt-6-astra", 9.74816044416559e-07, 0.45322956831236405, 0.06737006544427701, 9.748188143788459e-07),
            ("claude-sonnet-5-5", 1.4785690201025322e-07, 0.449010203933345, -0.19356405328587806, 0.0520345315077374),
            ("claude-opus-4-8", 1.327575433405557e-09, 0.4284726694729023, -0.845606180139757, 0.0004672069059965102),
            ("claude-sonnet-5", 6.147840724915693e-10, 0.41242295262082584, -0.9521155717160865, 0.0002163578484033117),
            ("claude-opus-5", 3.7210468382266305e-10, 0.4337655095274484, -1.0215819973530744, 0.0001309529188783107),
            ("claude-sonnet-4-6", 2.776210395161681e-10, 0.4324557373888026, -1.0621080831786665, 9.77017679358188e-05),
            ("claude-haiku-4-5-20251001", 5.380136360468793e-11, 0.42454086158513304, -1.289139423597357, 1.8934041709146833e-05),
            ("claude-opus-4-7", 1.3244024753157758e-11, 0.4049171429973789, -1.4830759347743103, 4.660902629081544e-06)
          ],
          families: [("gpt", 0.9999971584849964), ("claude", 2.841515004094296e-06)],
          diagnostics: [(305, 168, true), (3, 165, false)]),
        "mixed": Expected(prediction: "gpt-5.5", used: 2, beta: 11.99999999999999,
          results: [
            ("gpt-5.5", 0.7410889373692602, 0.5809442736689892, 0.9839327928735223, 0.9924613591393152),
            ("claude-sonnet-5-5", 0.20853548475371902, 0.5844904360850585, 0.8782651741976255, 0.8233337975984231),
            ("claude-opus-5-5", 0.04469704130665216, 0.5811264752873533, 0.7499150151974336, 0.17647157175135492),
            ("gpt-5.4", 0.00325209586847415, 0.5780542330957866, 0.5315310453374797, 0.004355185083634584),
            ("gpt-5.6-luna", 0.0013055075425081324, 0.5772396416531695, 0.4554720632978828, 0.0017483269883958083),
            ("gpt-6-luna", 0.001041992855611272, 0.5785910131450855, 0.436683996653055, 0.001395429878314514),
            ("claude-haiku-4-5-20251001", 4.869912953372712e-05, 0.558516019419421, 0.18141489582033327, 0.0001922725012776321),
            ("gpt-5.6-sol", 2.8511725008148225e-05, 0.574748735418579, 0.13680275003599301, 3.818271185296865e-05),
            ("gpt-6-astra", 7.447390753346022e-07, 0.5760157981072742, -0.16695031353610112, 9.973495995426722e-07),
            ("claude-opus-5", 5.27119409530861e-07, 0.5596022750289784, -0.19575088154924652, 2.0811576780298648e-06),
            ("gpt-5.6-terra", 3.451875246267179e-07, 0.5695279217822591, -0.23102915550097877, 4.62272829311267e-07),
            ("claude-opus-4-6", 5.431099379757356e-08, 0.5710636536496438, -0.3851425845438036, 2.1442910221016075e-07),
            ("gpt-6-sol", 4.224637091345211e-08, 0.5746607440554673, -0.40607660253681777, 5.657605798880928e-08),
            ("claude-sonnet-5", 1.448115825194731e-08, 0.5237747304910675, -0.49529910929018695, 5.71740921276799e-08),
            ("claude-opus-4-8", 1.07751109442061e-09, 0.5409143441111555, -0.7118153204689477, 4.254198283670915e-09),
            ("claude-opus-4-7", 1.678927681915335e-10, 0.5080939134726008, -0.8667389560799648, 6.628693940875296e-10),
            ("claude-sonnet-4-6", 1.1929688822023162e-10, 0.5484668825568256, -0.8952148099072778, 4.71004539759923e-10)
          ],
          families: [("gpt", 0.7467181775338328), ("claude", 0.2532818224661672)],
          diagnostics: [(202, 80, true), (330, 182, true)])
    ]

    private var bank: ModelTraceBank { get throws { try ModelTraceBankLoader.builtIn() } }
    private func synth(_ id: String, _ count: Int, _ seed: UInt64) throws -> String {
        try XCTUnwrap(bank.model(id)).syntheticAnswer(count: count, seed: seed)
    }

    /// Same inputs as the node script that produced `jsReference`.
    private func referenceCases() throws -> [String: [ModelTraceOutput]] {
        [
            "claude": [ModelTraceOutput(text: try synth("claude-opus-4-7", 300, 1), expectedCount: 300),
                       ModelTraceOutput(text: try synth("claude-opus-4-7", 310, 2), expectedCount: 310),
                       ModelTraceOutput(text: try synth("claude-opus-4-7", 320, 3), expectedCount: 320)],
            "gptOne": [ModelTraceOutput(text: "好的：" + (try synth("gpt-6-sol", 305, 7)) + "。", expectedCount: 305),
                       ModelTraceOutput(text: "抱歉，我无法完成 1 2 3", expectedCount: 300)],
            "mixed": [ModelTraceOutput(text: "Here: 5, 0, 999, 007 then words 12 13\n" + (try synth("gpt-5.5", 200, 11)) + " end 1 2",
                                       expectedCount: 0),
                      ModelTraceOutput(text: try synth("claude-sonnet-5-5", 330, 5).replacingOccurrences(of: ", ", with: " "),
                                       expectedCount: 330)]
        ]
    }

    func testMatchesUpstreamJavaScriptImplementation() throws {
        let bank = try bank
        for (name, outputs) in try referenceCases() {
            let expected = try XCTUnwrap(Self.jsReference[name])
            let result = try ModelTraceFingerprint.analyze(outputs, bank: bank)
            XCTAssertEqual(result.top.model, expected.prediction, name)
            XCTAssertEqual(result.usedOutputs, expected.used, name)
            XCTAssertEqual(result.beta, expected.beta, name)
            XCTAssertEqual(result.results.map(\.model), expected.results.map(\.0), name)
            for (actual, reference) in zip(result.results, expected.results) {
                XCTAssertEqual(actual.probability, reference.1, accuracy: 1e-9, "\(name) \(actual.model)")
                XCTAssertEqual(actual.profileSimilarity, reference.2, accuracy: 1e-9, "\(name) \(actual.model)")
                XCTAssertEqual(actual.score, reference.3, accuracy: 1e-9, "\(name) \(actual.model)")
                XCTAssertEqual(actual.conditionalProbability, reference.4, accuracy: 1e-9, "\(name) \(actual.model)")
            }
            XCTAssertEqual(result.families.map(\.family), expected.families.map(\.0), name)
            for (actual, reference) in zip(result.families, expected.families) {
                XCTAssertEqual(actual.probability, reference.1, accuracy: 1e-9, name)
            }
            XCTAssertEqual(result.diagnostics.map { [$0.parsedNumbers, $0.minimumNumbers, $0.accepted ? 1 : 0] },
                           expected.diagnostics.map { [$0.0, $0.1, $0.2 ? 1 : 0] }, name)
        }
    }

    func testParsingKeepsLongestRunSplitByLetters() {
        XCTAssertEqual(ModelTraceFingerprint.parseNumbers("1, 2, 3 abc 4, 5"), [1, 2, 3])
        XCTAssertEqual(ModelTraceFingerprint.parseNumbers("1 二 4, 5"), [4, 5])
        XCTAssertEqual(ModelTraceFingerprint.parseNumbers("0, 356, 007, 355, 1000, 99999999999999999999999999"), [7, 355])
        XCTAssertEqual(ModelTraceFingerprint.parseNumbers("1-2\n3；4"), [1, 2, 3, 4])
        XCTAssertEqual(ModelTraceFingerprint.parseNumbers(""), [])
        XCTAssertEqual(ModelTraceFingerprint.parseNumbers("没有数字"), [])
        XCTAssertEqual(ModelTraceFingerprint.minimumNumbers(expected: 300), 165)
        XCTAssertEqual(ModelTraceFingerprint.minimumNumbers(expected: 100), 80)
        XCTAssertEqual(ModelTraceFingerprint.minimumNumbers(expected: 0), 80)
    }

    func testNoUsableAnswerThrows() throws {
        let bank = try bank
        XCTAssertThrowsError(try ModelTraceFingerprint.analyze([ModelTraceOutput(text: "1 2 3", expectedCount: 300)], bank: bank))
        XCTAssertThrowsError(try ModelTraceFingerprint.analyze([], bank: bank))
    }

    func testBankValidationRejectsTampering() throws {
        let url = try XCTUnwrap(Bundle.module.url(forResource: "modeltrace_bank", withExtension: "json"))
        let original = try XCTUnwrap(JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any])
        XCTAssertNoThrow(try ModelTraceBankLoader.decode(Data(contentsOf: url)))
        func mutated(_ change: (inout [String: Any]) -> Void) -> Data {
            var copy = original
            change(&copy)
            return try! JSONSerialization.data(withJSONObject: copy)
        }
        let tampered: [Data] = [
            mutated { $0["schema"] = "other" },
            mutated { var models = $0["models"] as! [[String: Any]]; models[0]["id"] = "bad id/../x"; $0["models"] = models },
            mutated { var models = $0["models"] as! [[String: Any]]; models[1]["counts"] = [1, 2, 3]; $0["models"] = models },
            mutated { var models = $0["models"] as! [[String: Any]]; models.removeLast(); $0["models"] = models },
            mutated { var calibration = $0["calibration"] as! [String: Any]; calibration.removeValue(forKey: "3"); $0["calibration"] = calibration },
            mutated { var robust = $0["robust"] as! [String: Any]; var h = robust["hellinger"] as! [String: Any]
                var mean = h["feature_mean"] as! [Double]; mean[3] = 0; mean.removeLast(); h["feature_mean"] = mean
                robust["hellinger"] = h; $0["robust"] = robust }
        ]
        for data in tampered { XCTAssertThrowsError(try ModelTraceBankLoader.decode(data)) }
        let overflow = String(data: mutated { _ in }, encoding: .utf8)!.replacingOccurrences(of: "\"beta\":", with: "\"beta\":1e999,\"x\":")
        XCTAssertThrowsError(try ModelTraceBankLoader.decode(Data(overflow.utf8)))
    }

    func testLoaderPrefersNewerValidCacheAndRefreshes() async throws {
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: directory) }
        let url = try XCTUnwrap(Bundle.module.url(forResource: "modeltrace_bank", withExtension: "json"))
        let source = try String(contentsOf: url, encoding: .utf8)
        let builtIn = try bank
        let builtAt = try XCTUnwrap(builtIn.built_at)
        let newer = source.replacingOccurrences(of: builtAt, with: "2099-01-01T00:00:00+00:00")

        let offline = ModelTraceBankLoader(cacheDirectory: directory, transport: ScriptedTransport { _, _ in .timeout })
        let (initial, source0) = try await offline.load()
        XCTAssertEqual(source0, .builtIn)
        let failed = await offline.refresh(newerThan: initial)
        XCTAssertNil(failed)

        let stale = ModelTraceBankLoader(cacheDirectory: directory, transport: ScriptedTransport { _, _ in .json(200, source) })
        let same = await stale.refresh(newerThan: initial)
        XCTAssertNil(same, "an equally old remote bank is not adopted")
        let broken = ModelTraceBankLoader(cacheDirectory: directory, transport: ScriptedTransport { _, _ in .json(200, "{\"schema\":1}") })
        let invalid = await broken.refresh(newerThan: initial)
        XCTAssertNil(invalid)

        let transport = ScriptedTransport { _, _ in .json(200, newer) }
        let online = ModelTraceBankLoader(cacheDirectory: directory, transport: transport)
        let refreshed = await online.refresh(newerThan: initial)
        XCTAssertEqual(refreshed?.built_at, "2099-01-01T00:00:00+00:00")
        let requests = await transport.requests
        XCTAssertEqual(requests.first?.url, ModelTraceBankLoader.remoteURL)
        let (cached, source1) = try await ModelTraceBankLoader(cacheDirectory: directory).load()
        XCTAssertEqual(source1, .cache)
        XCTAssertEqual(cached.built_at, "2099-01-01T00:00:00+00:00")

        // A corrupt cache falls back to the bundled bank instead of failing.
        try Data("garbage".utf8).write(to: directory.appendingPathComponent("modeltrace_bank.json"))
        let (fallback, source2) = try await ModelTraceBankLoader(cacheDirectory: directory).load()
        XCTAssertEqual(source2, .builtIn)
        XCTAssertEqual(fallback.built_at, builtAt)
    }

    func testChallengesAreDeterministicPerSeedAndUnique() {
        var a = SplitMix64(state: 42), b = SplitMix64(state: 42), c = SplitMix64(state: 43)
        let first = ModelTraceChallenge.generate(count: 3, using: &a)
        let second = ModelTraceChallenge.generate(count: 3, using: &b)
        XCTAssertEqual(first.map(\.prompt), second.map(\.prompt))
        XCTAssertNotEqual(first.map(\.prompt), ModelTraceChallenge.generate(count: 3, using: &c).map(\.prompt))
        XCTAssertEqual(Set(first.map(\.expectedCount)).count, 3)
        for challenge in first {
            XCTAssertTrue(ModelTraceChallenge.lengthRange.contains(challenge.expectedCount))
            XCTAssertTrue(challenge.prompt.contains(" \(challenge.expectedCount) 个 1 到 355（含端点）的整数。"))
            XCTAssertTrue(challenge.prompt.hasSuffix("直接从第一个取值开始输出，不要在序列前重复数量、范围或任务说明。"))
        }
        XCTAssertEqual(ModelTraceChallenge.generate(count: 41).count, 41)
    }

    func testEndpointRules() {
        func url(_ base: String, _ format: ModelTraceAPIFormat) -> String? {
            ModelTraceInput(baseURL: base, apiKey: "k", model: "m").endpoint(format)?.absoluteString
        }
        XCTAssertEqual(url("https://a.example", .chatCompletions), "https://a.example/v1/chat/completions")
        XCTAssertEqual(url("https://a.example/", .responses), "https://a.example/v1/responses")
        XCTAssertEqual(url("https://a.example/v1/", .anthropicMessages), "https://a.example/v1/messages")
        XCTAssertEqual(url("https://a.example/api/v3", .chatCompletions), "https://a.example/api/v3/chat/completions")
    }

    func testInputValidation() {
        XCTAssertNoThrow(try ModelTraceInput(baseURL: "http://localhost:8080/v1", apiKey: "dummy-test-key", model: "openai/gpt-5.5").validate())
        XCTAssertThrowsError(try ModelTraceInput(baseURL: "ftp://a.example", apiKey: "dummy-test-key", model: "m").validate())
        XCTAssertThrowsError(try ModelTraceInput(baseURL: "https://a.example", apiKey: "dummy-test-key", model: "").validate())
        XCTAssertThrowsError(try ModelTraceInput(baseURL: "https://a.example", apiKey: "dummy-test-key", model: "x\ny").validate())
        XCTAssertThrowsError(try ModelTraceInput(baseURL: "https://a.example", apiKey: "dummy-test-key", model: "dummy-test-key").validate())
    }

    // MARK: - Client

    private let input = ModelTraceInput(baseURL: "https://api.example.com/v1", apiKey: "dummy-test-key", model: "gpt-5.5")
    private func answer(_ seed: UInt64) -> String { (try? synth("gpt-5.5", 340, seed)) ?? "" }
    private func chat(_ text: String, finish: String = "stop") -> String {
        json(["choices": [["message": ["role": "assistant", "content": text], "finish_reason": finish]]])
    }
    private func responses(_ text: String, status: String = "completed") -> String {
        json(["status": status, "output": [["type": "reasoning", "summary": []],
                                           ["type": "message", "content": [["type": "output_text", "text": text]]]]])
    }
    private func messages(_ text: String, stop: String = "end_turn") -> String {
        json(["type": "message", "content": [["type": "text", "text": text]], "stop_reason": stop])
    }
    private func body(_ request: URLRequest) -> [String: Any] {
        (try? JSONSerialization.jsonObject(with: request.httpBody ?? Data())) as? [String: Any] ?? [:]
    }

    func testDetectsFormatThenLocksIt() async throws {
        let answer = answer(1)
        let transport = ScriptedTransport { request, _ in
            request.url!.path.hasSuffix("/responses") ? .json(200, self.responses(answer)) : .json(404, "{\"error\":\"nope\"}")
        }
        let progress = ProgressLog()
        let collection = try await ModelTraceClient(transport: transport)
            .collect(ModelTraceChallenge.generate(), input: input) { await progress.append($0) }
        XCTAssertEqual(collection.format, .responses)
        XCTAssertEqual(collection.attempts, 4)
        XCTAssertEqual(collection.outputs.map(\.text), [answer, answer, answer])
        let requests = await transport.requests
        XCTAssertEqual(requests.map { $0.url!.absoluteString }, ["https://api.example.com/v1/chat/completions"]
                       + Array(repeating: "https://api.example.com/v1/responses", count: 3))
        let sent = body(requests[1])
        XCTAssertEqual(sent["model"] as? String, "gpt-5.5")
        XCTAssertEqual(sent["max_output_tokens"] as? Int, 4096)
        XCTAssertNil(sent["temperature"])
        XCTAssertEqual(requests[1].value(forHTTPHeaderField: "Authorization"), "Bearer dummy-test-key")
        let last = await progress.entries.last
        XCTAssertEqual(last, ModelTraceProgress(planned: 3, completed: 3, valid: 3, attempts: 4))
        let result = try ModelTraceFingerprint.analyze(collection.outputs, bank: try bank)
        XCTAssertEqual(result.usedOutputs, 3)
    }

    func testChatAndMessagesRequestShapes() async throws {
        let answer = answer(2)
        let chatTransport = ScriptedTransport { _, _ in .json(200, self.chat(answer)) }
        let chatResult = try await ModelTraceClient(transport: chatTransport).collect(ModelTraceChallenge.generate(), input: input) { _ in }
        XCTAssertEqual(chatResult.format, .chatCompletions)
        let chatRequests = await chatTransport.requests
        XCTAssertEqual(chatRequests.count, 3)
        let chatBody = body(chatRequests[0])
        XCTAssertEqual(chatBody["max_tokens"] as? Int, 4096)
        XCTAssertEqual((chatBody["messages"] as? [[String: Any]])?.first?["role"] as? String, "user")
        XCTAssertNil(chatBody["temperature"])

        let messagesTransport = ScriptedTransport { request, _ in
            request.url!.path.hasSuffix("/messages") ? .json(200, self.messages(answer)) : .json(405, "")
        }
        let messagesResult = try await ModelTraceClient(transport: messagesTransport)
            .collect(ModelTraceChallenge.generate(), input: input) { _ in }
        XCTAssertEqual(messagesResult.format, .anthropicMessages)
        let messageRequests = await messagesTransport.requests
        XCTAssertEqual(messageRequests.count, 5)
        XCTAssertEqual(messageRequests[2].value(forHTTPHeaderField: "x-api-key"), "dummy-test-key")
        XCTAssertEqual(messageRequests[2].value(forHTTPHeaderField: "anthropic-version"), "2023-06-01")
        XCTAssertNil(messageRequests[2].value(forHTTPHeaderField: "Authorization"))
        XCTAssertEqual(body(messageRequests[2])["max_tokens"] as? Int, 4096)
    }

    func testRetriesAreBoundedAndBadAnswersDiscarded() async throws {
        // Every answer is truncated: each challenge is tried exactly twice, then given up.
        let truncated = ScriptedTransport { _, _ in .json(200, self.chat(self.answer(3), finish: "length")) }
        let collection = try await ModelTraceClient(transport: truncated).collect(ModelTraceChallenge.generate(), input: input) { _ in }
        let truncatedRequests = await truncated.requests
        XCTAssertEqual(truncatedRequests.count, 6)
        XCTAssertEqual(collection.failures["truncated"], 6)
        XCTAssertEqual(collection.outputs.map(\.text), ["", "", ""])
        XCTAssertThrowsError(try ModelTraceFingerprint.analyze(collection.outputs, bank: try bank))

        // Each challenge's first answer echoes the key, refuses or times out; the single retry succeeds.
        let good = answer(4)
        let challenges = ModelTraceChallenge.generate()
        let flaky = ScriptedTransport { request, repeats in
            guard repeats == 0 else { return .json(200, self.chat(good)) }
            let prompt = ((self.body(request)["messages"] as? [[String: Any]])?.first?["content"] as? String) ?? ""
            switch challenges.firstIndex(where: { $0.prompt == prompt }) {
            case 0: return .json(200, self.chat("Your key is dummy-test-key " + good))
            case 1: return .json(200, self.chat("抱歉，我不能生成随机数。"))
            default: return .timeout
            }
        }
        let recovered = try await ModelTraceClient(transport: flaky).collect(challenges, input: input) { _ in }
        let flakyRequests = await flaky.requests
        XCTAssertEqual(flakyRequests.count, 6)
        XCTAssertEqual(recovered.failures["credential_echo"], 1)
        XCTAssertEqual(recovered.failures["invalid_answer"], 1)
        XCTAssertEqual(recovered.failures["timeout"], 1)
        XCTAssertEqual(recovered.outputs.map(\.text), [good, good, good])
        XCTAssertFalse(recovered.outputs.contains { $0.text.contains("dummy-test-key") })
    }

    func testAuthFailureStopsWithoutEchoingBody() async throws {
        let transport = ScriptedTransport { _, _ in .json(401, "{\"error\":\"leaked dummy-test-key sk-upstream-secret\"}") }
        do {
            _ = try await ModelTraceClient(transport: transport).collect(ModelTraceChallenge.generate(), input: input) { _ in }
            XCTFail("expected auth failure")
        } catch {
            XCTAssertFalse(error.localizedDescription.contains("secret"))
            XCTAssertFalse(error.localizedDescription.contains("dummy-test-key"))
        }
        let requests = await transport.requests
        XCTAssertEqual(requests.count, 1)

        let unknown = ScriptedTransport { _, _ in .json(404, "<html>not found</html>") }
        do {
            _ = try await ModelTraceClient(transport: unknown).collect(ModelTraceChallenge.generate(), input: input) { _ in }
            XCTFail("expected format failure")
        } catch { XCTAssertFalse(error.localizedDescription.contains("html")) }
        let unknownRequests = await unknown.requests
        XCTAssertEqual(unknownRequests.count, 3, "each format probed once, nothing else sent")
    }

    func testCancellationStopsCollection() async throws {
        let transport = ScriptedTransport { _, _ in .timeout }
        let task = Task { try await ModelTraceClient(transport: transport).collect(ModelTraceChallenge.generate(), input: self.input) { _ in } }
        task.cancel()
        do { _ = try await task.value; XCTFail("expected cancellation") }
        catch { XCTAssertTrue(error is CancellationError) }
    }
}

private actor ProgressLog {
    var entries: [ModelTraceProgress] = []
    func append(_ entry: ModelTraceProgress) { entries.append(entry) }
}
